apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  resourceRegistration: dp

  health:
    coreTemperatureThreshold: 88

  dp:
    plugin: docker.io/intel/intel-gpu-plugin:0.36.0@sha256:2db679be62b52ac985169084ca711cab6e6c59fe543ab2ddee58163d6f8d29e0
    byPathMode: single

    logLevel: 4
