apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-{{ .Values.resourceRegistration }}
spec:
  resourceRegistration: {{ .Values.resourceRegistration }}
  useNFDLabeling: {{ .Values.useNFDLabeling }}
  resourceMonitoring: {{ .Values.resourceMonitoring }}
  prometheusIntegration: {{ .Values.prometheusIntegration }}
  enableKueue: {{ .Values.enableKueue }}

  {{- if .Values.kueue }}
  kueue:
    equalResources:
    {{- range $clusterQueue := .Values.kueue.equalResources }}
      - name: {{ $clusterQueue.name }}
        localQueues:
        {{- range $localQueue := $clusterQueue.localQueues }}
          - name: {{ $localQueue.name }}
            namespace: {{ $localQueue.namespace }}
        {{- end }}
    {{- end }}
  {{- end }}

  logLevel: {{ .Values.logLevel }}

  health:
    checkIntervalSeconds: {{ .Values.health.checkIntervalSeconds }}
    coreTemperatureThreshold: {{ .Values.health.coreTemperatureThreshold }}
    memoryTemperatureThreshold: {{ .Values.health.memoryTemperatureThreshold }}

{{- if eq .Values.resourceRegistration "dp" }}
  dp:
    plugin: {{ .Values.dp.plugin }}
    logLevel: {{ .Values.dp.logLevel }}
    byPathMode: {{ .Values.dp.byPathMode }}
{{- if .Values.dp.allowIDs }}
    allowIDs:
{{ toYaml .Values.dp.allowIDs | default "[]" | indent 6 }}
{{- end }}
{{- if .Values.dp.denyIDs }}
    denyIDs:
{{ toYaml .Values.dp.denyIDs | default "[]" | indent 6 }}
{{- end }}
{{- else if eq .Values.resourceRegistration "dra" }}
  dra:
    image: {{ .Values.dra.image }}
    logLevel: {{ .Values.dra.logLevel }}
    podHealthCheck: {{ .Values.dra.podHealthCheck | default true }}
    manageBinding: {{ .Values.dra.manageBinding | default false }}
{{- else }}
    {{- fail "Please select either dp or dra" }}
{{- end }}

  xpu:
    image: {{ .Values.xpu.image }}
    logLevel: {{ .Values.xpu.logLevel }}
{{- if .Values.xpu.monitoringResource }}
    monitoringResource: {{ .Values.xpu.monitoringResource | quote }}
{{- end }}
{{- if .Values.xpu.configMapOverride }}
    configMapOverride: {{ .Values.xpu.configMapOverride | default "" }}
{{- end }}

{{- if .Values.kernelModule }}
  kernelModule:
    moduleName: {{ .Values.kernelModule.moduleName }}
    {{- if .Values.kernelModule.version }}
    version: {{ .Values.kernelModule.version | quote }}
    {{- end }}
    kernelMappings:
    {{- range .Values.kernelModule.kernelMappings }}
      - regexp: {{ .regexp | quote }}
        {{- if .containerImage }}
        containerImage: {{ .containerImage }}
        {{- end }}
        {{- if .build }}
        build:
          dockerfileConfigMap:
            name: {{ .build.dockerfileConfigMap.name }}
          {{- if .build.buildArgs }}
          buildArgs:
          {{- range .build.buildArgs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if .build.secrets }}
          secrets:
          {{- range .build.secrets }}
            - name: {{ .name }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .inTreeModulesToRemove }}
        inTreeModulesToRemove: {{ toYaml .inTreeModulesToRemove | nindent 10 }}
        {{- end }}
        {{- if .registryTLS }}
        registryTLS:
          {{- if .registryTLS.insecure }}
          insecure: {{ .registryTLS.insecure }}
          {{- end }}
          {{- if .registryTLS.insecureSkipTLSVerify }}
          insecureSkipTLSVerify: {{ .registryTLS.insecureSkipTLSVerify }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- if .Values.kernelModule.modulesLoadingOrder }}
    modulesLoadingOrder: {{ toYaml .Values.kernelModule.modulesLoadingOrder | nindent 6 }}
    {{- end }}
    {{- if .Values.kernelModule.firmwarePath }}
    firmwarePath: {{ .Values.kernelModule.firmwarePath }}
    {{- end }}
    {{- if .Values.kernelModule.registryTLS }}
    registryTLS:
      {{- if .Values.kernelModule.registryTLS.insecure }}
      insecure: {{ .Values.kernelModule.registryTLS.insecure }}
      {{- end }}
      {{- if .Values.kernelModule.registryTLS.insecureSkipTLSVerify }}
      insecureSkipTLSVerify: {{ .Values.kernelModule.registryTLS.insecureSkipTLSVerify }}
      {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.pullSecret }}
  pullSecret: {{ .Values.pullSecret }}
{{- end }}
{{- if .Values.nodeSelector }}
  nodeSelector: {{ toYaml .Values.nodeSelector | nindent 4 }}
{{- end }}
{{- if .Values.tolerations }}
  tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
{{- end }}
