# Default values for gpu-base-operator.

createNamespace: true

nfd:
  install: false
  postDeleteCleanup: false

operator:
  image:
    repository: ghcr.io/intel/intel-gpu-base-operator:devel
    pullPolicy: IfNotPresent
  verbosity: 2
  resources:
    limits:
      cpu: 200m
      memory: 386Mi
    requests:
      cpu: 100m
      memory: 256Mi

privateRegistry:
  url: ""
  user: ""
  token: ""

kueue:
  install: false
  managerConfig:
    # -- controller_manager_config.yaml.
    # ControllerManager utilizes this yaml via manager-config Configmap.
    # @default -- controllerManagerConfigYaml
    #
    # Original Kueue v0.19 managerConfig from
    # https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/values.yaml#L113
    controllerManagerConfigYaml: |-
      apiVersion: config.kueue.x-k8s.io/v1beta2
      kind: Configuration
      health:
        healthProbeBindAddress: :8081
      metrics:
        bindAddress: :8443
      webhook:
        port: 9443
      leaderElection:
        leaderElect: true
        resourceName: c1f6bfd2.kueue.x-k8s.io
      controller:
        groupKindConcurrency:
          Job.batch: 5
          Pod: 5
          Workload.kueue.x-k8s.io: 10
          LocalQueue.kueue.x-k8s.io: 5
          ClusterQueue.kueue.x-k8s.io: 5
          ResourceFlavor.kueue.x-k8s.io: 1
      clientConnection:
        qps: 300
        burst: 500
      integrations:
        frameworks:
        - "batch/job"
        - "kubeflow.org/mpijob"
        - "ray.io/rayjob"
        - "ray.io/rayservice"
        - "ray.io/raycluster"
        - "jobset.x-k8s.io/jobset"
        - "trainer.kubeflow.org/trainjob"
        - "workload.codeflare.dev/appwrapper"
        - "pod"
        - "deployment"
        - "statefulset"
        - "leaderworkerset.x-k8s.io/leaderworkerset"
      # deviceClassMappings set by https://github.com/intel/gpu-base-operator
      resources:
        deviceClassMappings:
        - deviceClassNames:
          - "gpu.intel.com"
          name: "dra.gpu.intel.com"
