//go:build !ignore_autogenerated

/*
Copyright 2025 Intel Corporation. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicy) DeepCopyInto(out *ClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicy.
func (in *ClusterPolicy) DeepCopy() *ClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyCustomDefaulter) DeepCopyInto(out *ClusterPolicyCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyCustomDefaulter.
func (in *ClusterPolicyCustomDefaulter) DeepCopy() *ClusterPolicyCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyCustomValidator) DeepCopyInto(out *ClusterPolicyCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyCustomValidator.
func (in *ClusterPolicyCustomValidator) DeepCopy() *ClusterPolicyCustomValidator {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyList) DeepCopyInto(out *ClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyList.
func (in *ClusterPolicyList) DeepCopy() *ClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicySpec) DeepCopyInto(out *ClusterPolicySpec) {
	*out = *in
	if in.Kueue != nil {
		in, out := &in.Kueue, &out.Kueue
		*out = new(KueueQueueSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthinessSpec != nil {
		in, out := &in.HealthinessSpec, &out.HealthinessSpec
		*out = new(HealthinessSpec)
		**out = **in
	}
	out.DynamicResourceAllocationSpec = in.DynamicResourceAllocationSpec
	in.DevicePluginSpec.DeepCopyInto(&out.DevicePluginSpec)
	out.XpuManagerSpec = in.XpuManagerSpec
	if in.PullSecret != nil {
		in, out := &in.PullSecret, &out.PullSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicySpec.
func (in *ClusterPolicySpec) DeepCopy() *ClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPolicyStatus) DeepCopyInto(out *ClusterPolicyStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPolicyStatus.
func (in *ClusterPolicyStatus) DeepCopy() *ClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterQueueSpec) DeepCopyInto(out *ClusterQueueSpec) {
	*out = *in
	if in.LocalQueues != nil {
		in, out := &in.LocalQueues, &out.LocalQueues
		*out = make([]LocalQueueSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterQueueSpec.
func (in *ClusterQueueSpec) DeepCopy() *ClusterQueueSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePluginSpec) DeepCopyInto(out *DevicePluginSpec) {
	*out = *in
	if in.AllowIDs != nil {
		in, out := &in.AllowIDs, &out.AllowIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyIDs != nil {
		in, out := &in.DenyIDs, &out.DenyIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePluginSpec.
func (in *DevicePluginSpec) DeepCopy() *DevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResourceAllocationSpec) DeepCopyInto(out *DynamicResourceAllocationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResourceAllocationSpec.
func (in *DynamicResourceAllocationSpec) DeepCopy() *DynamicResourceAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicResourceAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareContent) DeepCopyInto(out *GPUFirmwareContent) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]GPUFirmwareFile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareContent.
func (in *GPUFirmwareContent) DeepCopy() *GPUFirmwareContent {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareFile) DeepCopyInto(out *GPUFirmwareFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareFile.
func (in *GPUFirmwareFile) DeepCopy() *GPUFirmwareFile {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdate) DeepCopyInto(out *GPUFirmwareUpdate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdate.
func (in *GPUFirmwareUpdate) DeepCopy() *GPUFirmwareUpdate {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUFirmwareUpdate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdateCustomValidator) DeepCopyInto(out *GPUFirmwareUpdateCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdateCustomValidator.
func (in *GPUFirmwareUpdateCustomValidator) DeepCopy() *GPUFirmwareUpdateCustomValidator {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdateCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdateList) DeepCopyInto(out *GPUFirmwareUpdateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUFirmwareUpdate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdateList.
func (in *GPUFirmwareUpdateList) DeepCopy() *GPUFirmwareUpdateList {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUFirmwareUpdateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdateSpec) DeepCopyInto(out *GPUFirmwareUpdateSpec) {
	*out = *in
	in.Content.DeepCopyInto(&out.Content)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdateSpec.
func (in *GPUFirmwareUpdateSpec) DeepCopy() *GPUFirmwareUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdateStatus) DeepCopyInto(out *GPUFirmwareUpdateStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NodeInfos.DeepCopyInto(&out.NodeInfos)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdateStatus.
func (in *GPUFirmwareUpdateStatus) DeepCopy() *GPUFirmwareUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFirmwareUpdateSubsetStatus) DeepCopyInto(out *GPUFirmwareUpdateSubsetStatus) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Draining != nil {
		in, out := &in.Draining, &out.Draining
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Updating != nil {
		in, out := &in.Updating, &out.Updating
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFirmwareUpdateSubsetStatus.
func (in *GPUFirmwareUpdateSubsetStatus) DeepCopy() *GPUFirmwareUpdateSubsetStatus {
	if in == nil {
		return nil
	}
	out := new(GPUFirmwareUpdateSubsetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthinessSpec) DeepCopyInto(out *HealthinessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthinessSpec.
func (in *HealthinessSpec) DeepCopy() *HealthinessSpec {
	if in == nil {
		return nil
	}
	out := new(HealthinessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueQueueSpec) DeepCopyInto(out *KueueQueueSpec) {
	*out = *in
	if in.EqualResources != nil {
		in, out := &in.EqualResources, &out.EqualResources
		*out = make([]ClusterQueueSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueQueueSpec.
func (in *KueueQueueSpec) DeepCopy() *KueueQueueSpec {
	if in == nil {
		return nil
	}
	out := new(KueueQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalQueueSpec) DeepCopyInto(out *LocalQueueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalQueueSpec.
func (in *LocalQueueSpec) DeepCopy() *LocalQueueSpec {
	if in == nil {
		return nil
	}
	out := new(LocalQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XpuManagerSpec) DeepCopyInto(out *XpuManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XpuManagerSpec.
func (in *XpuManagerSpec) DeepCopy() *XpuManagerSpec {
	if in == nil {
		return nil
	}
	out := new(XpuManagerSpec)
	in.DeepCopyInto(out)
	return out
}
