apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-devices
spec:
  rules:
    - name: "intel.gpu"
      labels:
        "intel.feature.node.kubernetes.io/gpu": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300", "0380"]}
      matchAny:
        - matchFeatures:
          - feature: kernel.loadedmodule
            matchExpressions:
              i915: {op: Exists}
        - matchFeatures:
          - feature: kernel.enabledmodule
            matchExpressions:
              i915: {op: Exists}
        - matchFeatures:
          - feature: kernel.loadedmodule
            matchExpressions:
              xe: {op: Exists}
        - matchFeatures:
          - feature: kernel.enabledmodule
            matchExpressions:
              xe: {op: Exists}
    - name: "intel.gpu.without-driver"
      labels:
        "intel.feature.node.kubernetes.io/gpu-pci": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300", "0380"]}
    # Assumes there are only one model of GPU per node.
    # source: https://dgpu-docs.intel.com/overview/supported-hardware/xe-driver-gpus.html
    - name: "intel.gpu.pro.b50"
      labels:
        "gpu.intel.com/product": "Arc_Pro_B50"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e212"]}
    - name: "intel.gpu.pro.b60"
      labels:
        "gpu.intel.com/product": "Arc_Pro_B60"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e211"]}
    - name: "intel.gpu.pro.b65"
      labels:
        "gpu.intel.com/product": "Arc_Pro_B65"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e222"]}
    - name: "intel.gpu.pro.b70"
      labels:
        "gpu.intel.com/product": "Arc_Pro_B70"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e223"]}
    - name: "intel.gpu.b370"
      labels:
        "gpu.intel.com/product": "Arc_B370"
        "gpu.intel.com/architecture": "Xe3"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["b081","b083","b085","b087"]}
    - name: "intel.gpu.b390"
      labels:
        "gpu.intel.com/product": "Arc_B390"
        "gpu.intel.com/architecture": "Xe3"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["b080","b082","b084","b086"]}
    - name: "intel.gpu.b570"
      labels:
        "gpu.intel.com/product": "Arc_B570"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e20c"]}
    - name: "intel.gpu.b580"
      labels:
        "gpu.intel.com/product": "Arc_B580"
        "gpu.intel.com/architecture": "Xe2"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["8086"]}
            class: {op: In, value: ["0300"]}
            device: {op: In, value: ["e20b"]}
