{{- if .Values.moduleLoader.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.moduleLoader.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: intel-gpu-base-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
