{{- if .Values.openshift.enabled }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ .Release.Name }}-module-loader-scc
  labels:
    app.kubernetes.io/name: intel-gpu-base-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowedCapabilities:
  - SYS_MODULE
defaultAddCapabilities: null
requiredDropCapabilities: null
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - "*"
supplementalGroups:
  type: RunAsAny
volumes:
  - hostPath
  - configMap
  - secret
  - projected
  - emptyDir
  - downwardAPI
users: []
groups: []
{{- end }}
