apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: intel-gpu-base-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
