---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: intel-gpu-base-operator
  name: intel-gpu-base-operator-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: intel-gpu-base-operator
    control-plane: {{ .Release.Name }}-controller-manager
