apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  resourceRegistration: dra
  logLevel: 4

  health:
    coreTemperatureThreshold: 89
    memoryTemperatureThreshold: 99
    checkIntervalSeconds: 12

  dra:
    image: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver:v0.11.0@sha256:49f38fcbee4f98d748b537b1a728a12f39e56fd208c86dc3fa32ab2162c21197
    logLevel: 2
    deviceTaints: false
    podHealthCheck: true
