apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  resourceRegistration: dra
  logLevel: 4

  health:
    coreTemperatureThreshold: 89
    memoryTemperatureThreshold: 99
    checkIntervalSeconds: 12

  dra:
    image: ghcr.io/intel/intel-gpu-resource-driver:v0.12.0@sha256:5be06e1cf810c6091cec17ed78a775be64323f2084038c8840f283f643ce4207
    logLevel: 2
    podHealthCheck: true
