apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  useNFDLabeling: false
  resourceMonitoring: true
  prometheusIntegration: false
  enableKueue: false
  logLevel: 2

  health:
    coreTemperatureThreshold: 100
    memoryTemperatureThreshold: 100
    checkIntervalSeconds: 5

  xpu:
    image: ghcr.io/intel/xpumanager/xpumd:v2.2.0@sha256:fdefec8e5d93f76a1c7b4dda56001b7f3c2c15eae29bfbbc8971b900e6e74ae8
    logLevel: 2
    # Device Plugin monitoring resource.
    monitoringResource: monitoring
