apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  useNFDLabeling: false
  resourceMonitoring: true
  prometheusIntegration: false
  enableKueue: false
  logLevel: 2

  health:
    coreTemperatureThreshold: 100
    memoryTemperatureThreshold: 100
    checkIntervalSeconds: 5

  xpu:
    image: ghcr.io/intel/xpumanager/xpumd:v2.0.0@sha256:bd6bad4f95274832ce6863c6f7744fc73a610903617d9def2932588138be0b85
    logLevel: 2
    # Device Plugin monitoring resource.
    monitoringResource: monitoring
