name: Build and Push (self-hosted)
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch:

permissions: {}

jobs:
  push:
    name: Publish Operator image
    permissions:
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
      contents: read
      packages: write
      id-token: write # for cosign to get an OIDC token from Actions
    uses: "./.github/workflows/build-push-common.yaml"
    with:
      runner: self-hosted
    secrets: inherit
