name: Build and Push (public)
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions: {}

jobs:
  push:
    name: Publish Operator image
    permissions:
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
      contents: read
      packages: write
    uses: "./.github/workflows/build-push-common.yaml"
    with:
      runner: ubuntu-24.04
    secrets: inherit
