name: Package and upload helm

on:
  workflow_dispatch:
    inputs:
      runner:
        default: "self-hosted"
        required: false
        type: string

permissions: {}

env:
  REGISTRY: ${{ vars.REGISTRY }}
  PROJECT: ${{ vars.PROJECT }}
  # Used by the Makefile
  RELEASE_REGISTRY: ${{ vars.REGISTRY }}/${{ vars.PROJECT }}

jobs:
  push-helm-charts:
    runs-on: ${{ inputs.runner }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          fetch-tags: true

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        if: inputs.runner != 'self-hosted'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push packaged Helm chart
        run: make helm-push-chart

      - name: Push packaged Helm policy chart
        run: make helm-push-policy-chart