name: Validation with self-hosted runner
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions: {}

env:
  LOCALBIN: /runners/tools/bin

jobs:
  validate:
    permissions:
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
      contents: read
    uses: "./.github/workflows/validate-common.yaml"
    with:
      runner: self-hosted

  e2e:
    needs: validate
    permissions:
      pull-requests: read
      contents: read
    uses: "./.github/workflows/validate-e2e.yaml"
    with:
      runner: kubernetes-gpu-ci
      runtarget: ${{ github.event_name == 'pull_request' && 'test-e2e' || 'test-e2e-extended' }}
