name: validation e2e
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        default: kubernetes-gpu-ci
      runtarget:
        required: false
        type: string
        default: test-e2e

permissions: {}

jobs:
  e2e:
    name: Run e2e with GPU HW
    runs-on: ${{ inputs.runner }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          clean: true
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
      - name: Build operator container
        run: |
          make docker-build
      - name: Install dependencies
        run: |
          mkdir -p $(pwd)/bin
          export PATH=$PATH:$(pwd)/bin
          make helm kind
      - name: Update helm dependencies
        run: |
          export PATH=$PATH:$(pwd)/bin
          helm dep update ./charts/gpu-base-operator
      - name: Run e2e tests
        run: |
          export PATH=$PATH:$(pwd)/bin
          make ${{ inputs.runtarget }}
      - name: Tear down Kind cluster
        if: always()
        continue-on-error: true
        run: |
          make cleanup-test-e2e
