name: Validation with public runner
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
      contents: read
    uses: "./.github/workflows/validate-common.yaml"
    with:
      runner: ubuntu-24.04
